const { merge } = require('webpack-merge')

const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin')

const commonConfig = require('./webpack.common')

// Configuration specific to local development
const devConfig = {
  mode: 'development',
  devServer: {
    port: 8080,
    // changes all incoming non-file requests to route to index.htlm (by default) for direct
    // url access in SPA's
    historyApiFallback: true,
  },
  output: {
    // make sure that in development we set the publicpath to / so that if the FE has segmented URLs e.g. /blog/blogpost
    // the browser knows to look for the main.js generated by webpack at the project root rather than at /auth/main.js
    publicPath: 'http://localhost:8080/',
  },
  plugins: [
    // Module federation plugin is doing all the magic to wire up our micro front ends
    // TODO:
  ],
}

module.exports = merge(commonConfig, devConfig)
